config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
      get :users, on: :collection
      get :assign_user, on: :member
      get :remove_user, on: :member
    resource :bugs do
      get :assign_bug, on: :member
      get :mark_resolved, on: :member
    end
  end

  root "projects#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :developer, optional: true
  belongs_to :qa

  mount_uploader :image, ImageUploader
  validates :title, presence: true,
                    length: {minimum: 5}, uniqueness: true
  validate  :deadline_cannot_be_in_the_past

  def deadline_cannot_be_in_the_past
    errors.add(:deadline, "can't be in the past") if
      deadline.present? and deadline < Date.today
  end
end 
 

app/models/developer.rb
class Developer < User
  has_and_belongs_to_many :projects, join_table: "developers_projects"
  has_many :bugs
end

app/models/manager.rb
class Manager < User
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :bugs, dependent: :delete_all
  has_and_belongs_to_many :qas, join_table: "projects_qas"
  has_and_belongs_to_many :developers, join_table: "developers_projects"
  belongs_to :manager
  
  validates :title, presence: true,
                  length: {minimum: 5}
end
 

app/models/qa.rb
class Qa < User
  has_and_belongs_to_many :projects,join_table: "projects_qas"
  has_many :bugs
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :type, inclusion: { in: ["Manager", "Qa", "Developer"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    include Pundit
    protect_from_forgery

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def user_not_authorized
        flash[:alert] = 'You are not authorized to perform this action.'
        redirect_back(fallback_location: root_path)
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:type])
    end

    
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project
  before_action :find_bug, except: [:new, :create]
  
  def new
    @bug = @project.bugs.new
    authorize @bug
  end
  
  def create
    @bug = @project.bugs.new(bug_params)
    authorize @bug
    @bug.qa_id = current_user.id
    
    if @bug.save
      redirect_to @project
    else
      render 'new'
    end  
  end
  
  def show

  end

  def edit
    
  end
  
  def update
    if @bug.update(bug_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @bug.destroy

    redirect_to project_path(@project)
  end
 
  def assign_bug
    @user = User.find(params[:user_id])
    @bug.developer_id = @user.id
    @bug.status = "Started"
    
    if @bug.save
      redirect_to project_path(@project)
    end
  end

  def mark_resolved
    if @bug.bug_type == "Feature"
      @bug.status = "Completed"
    else
      @bug.status = "Resolved"
    end

    if @bug.save
      redirect_to project_path(@project)
    else
      redirect_to projects_path
    end

  end

  private
    def bug_params
      params.require(:bug).permit(:title, :deadline, :image, :bug_type, :status)
    end
  
    def find_project
      @project = Project.find(params[:project_id])
    end
  
    def find_bug
      @bug = @project.bugs.find(params[:bug_id])
      authorize @bug
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, except: [:index, :new, :create, :remove_user]

  def index
    get_projects
  end

  def show

  end

  def new
    @project = current_user.projects.build
    authorize @project
  end

  def edit

  end
 
  def create
    @project = current_user.projects.build(project_params)
    @project.manager_id = current_user.id

    if @project.save
      redirect_to @project
    else
      render "new"
    end
  end
   
  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render "edit"
    end
  end

  def destroy  
    @project.destroy
  
    redirect_to projects_path
  end

  def users
    get_users(@project)
  end
  
  def assign_user
    @user = User.find(params[:user_id])

    if @user.type == "Developer"
      @project.developers << @user
    else @user.type == "Qa"
      @project.qas << @user
    end
  
      redirect_to project_path(@project)
  end

  def remove_user
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    authorize @project
    if @user.type == "Developer"
      assigned_projects(@user, @project)
    end
    if @user.type == "Developer"
      @project.developers.delete(@user)
    else @user.type == "Qa"
      @project.qas.delete(@user)
    end
    redirect_to project_path(@project)
  end

  private
    def project_params
      params.require(:project).permit(:title, :description, :code)
    end

    def assigned_projects(user, project)
      @bugs = project.bugs.all
      project.bugs.each do |bug| 
        if bug.developer_id == user.id
          bug.developer_id = nil
          bug.save
          if bug.status == "Started"
            bug.status = "New"
            bug.save
          end
        end
      end
    end
    
    def find_project
      @project = Project.find(params[:id])
      authorize @project
    end

    def get_projects
      @allprojects = Project.all
      @projects = @allprojects.select do |project|
        project.manager_id == current_user.id || project.qas.include?(current_user) || project.developers.include?(current_user)
      end
      @projects
    end

    def get_users(project)
      @allusers = User.all
      @users = @allusers.select do |user|
        user.type != "Manager" && user != current_user && ! ( project.qas.include?(user) || project.developers.include?(user) )
      end
      @users
    end

    def authorize_project
      authorize @project
    end
end
   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_bug.html.erb
    
    <tr>
        <td><%= bug.title %></td>
        <td><%= bug.deadline %></td>
        <td><%= bug.bug_type %></td>
        <td><%= bug.status %></td>
        <td><%= link_to "Show", project_bugs_path(:bug_id => bug.id, :project_id => @project.id) %></td>
        <% if policy(bug).edit?  %>
            <td><%= link_to "Edit", edit_project_bugs_path(:bug_id => bug.id, :project_id => @project.id) %></td>
        <% end %>
        <% if policy(bug).destroy?  %>
            <td><%= link_to "Destroy", project_bugs_path(:bug_id => bug.id, :project_id => @project.id),
                    method: :delete,
                    data: { confirm: "Are you sure?"} %></td>
        <% end %>
    </tr>

    <% if false %>
        <p>
            <strong>Bug Title: </strong>
            <%= bug.title %>
        </p>
        <p>
            <strong>Deadline: </strong>
            <%= bug.deadline %>
        </p>
        <p>
            <strong>Screenshot: </strong>
            <%= image_tag bug.image_url(:thumb).to_s %>
        </p>
        <p>
            <strong>Type: </strong>
            <%= bug.bug_type %>
        </p>
        <p>
            <strong>status: </strong>
            <%= bug.status %>
        </p>
        <% if current_user.role =="Developer" && bug.user_id.nil? && bug.status == 'New'  %>
            <%= link_to "Assign Bug", assign_bug_project_bug_path(:user_id => current_user.id, :bug_id => bug.id, :project_id => @project.id) %>
        <% end %>

        <% unless bug.user_id.nil?%>
            <p>
                <strong>Assigned To: </strong>
                <% @user = User.find(bug.user_id) %>
                <%= @user.email %>
            </p>
        <% end %>
    <% end %>  

app/views/bugs/_error.html.erb
<%= link_to project_path(@project), style: "float: right;" do%>
    <i class = "glyphicon glyphicon-remove"></i>
<% end %>

<% if @bug.errors.any? %>
    <div id = "error_explanation">
        <h4>
            The following 
            <%= pluralize(@bug.errors.count, "error") %>
            prohibited this bug from being saved :
        </h4>
        <ul>
            <% @bug.errors.full_messages.each do |message|%>
                <li><%= message %>.</li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/bugs/_form.html.erb
<%= form_with(url: project_bugs_path(@project, @bug), html: {class: "text-center border border-light p-5", multipart: true}, local: true, model: [@project, @bug] ) do |f| %>  
    <div class = "form-group">
        <%= f.label :Title, style: "float:left;" %>
        <%= f.text_field :title, class: "form-control mb-4",placeholder: "Add a descriptive title" %>
    </div>
    <div class = "form-group">
        <%= f.label :Deadline, style: "float:left;" %>
        <%= f.date_field :deadline, class: 'form-control rounded-0', 
        placeholder: 'Deadline'%>
    </div>
    <div class = "form-group">
        <%= f.label :Screenshot, style: "float:left;" %>
        <%= f.file_field :image %>
    </div>
    <div class = "form-group">
        <%= f.label :Type, style: "float:left; "%><br/>
        <div id = "radio">
            <div class = "form-check"> 
                <%= f.radio_button :bug_type, 'Feature', class: "form-check-input inactive", id: "materialChecked2" %>
                <%= f.label :Feature, class: "form-check-label", for: "materialChecked2" %>
            </div>
            <div class = "form-check"> 
                <%= f.radio_button :bug_type, 'Bug', class: "form-check-input active", id: "materialChecked2", style: "float:left;" %>
                <%= f.label "Bug", class: "form-check-label", for: "materialChecked2", style: "float:left;" %>
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <div class = "form-group">
        <%= f.label :Status, style: "float:left;" %>
        <%= f.select :status, [['New','New'], ['Started','Started'], ['Completed','Completed']], {}, class: "form-control status"  %>
    </div>
    <%= f.submit class: "btn btn-info btn-block" %>
<% end %>

app/views/bugs/edit.html.erb
<div class = "container">
    <div class = "jumbotron" style = "margin-top:3%;">

        <%= render "error" %>
        <p class = "h2 mb-4">Edit Bug for <%= @project.title %></p>
        <%= render "form" %>
    </div>
</div>

       

app/views/bugs/new.html.erb
<div class = "container">
    <div class = "jumbotron" style = "margin-top:3%;">

        <%= render "error" %>
        <p class = "h2 mb-4">New Bug for <%= @project.title %></p>
        <%= render "form" %>
    </div>
</div>  

app/views/bugs/show.html.erb
<div class = "container">
    <div class = "jumbotron" style = "margin-top:3%;">
        <p>
            <strong>Title:</strong>
            <%= @bug.title %>
        </p>
        <p>
            <strong>Deadline: </strong>
            <%= @bug.deadline %>
        </p>
        <p>
            <strong>Screenshot: </strong>
            <%= image_tag @bug.image_url(:thumb).to_s %>
        </p>
        <p>
            <strong>Type: </strong>
            <%= @bug.bug_type %>
        </p>
        <p>
            <strong>status: </strong>
            <%= @bug.status %>
        </p>
        <% if policy(@bug).assign_bug?   %>
            <%= link_to "Assign Bug", assign_bug_project_bugs_path(:user_id => current_user.id, :bug_id => @bug.id, :project_id => @project.id) %>
        <% end %>

       

        <%if @bug.developer %>
            <p>
                <strong>Assigned To: </strong>
                <%= @bug.developer.email %>
            </p>
        <% end %>
        <% if policy(@bug).mark_resolved?  %>
            <%= link_to "Mark Resolved/Completed", mark_resolved_project_bugs_path(:bug_id => @bug.id, :project_id => @project.id) %>
        <% end %>
        <%= link_to "Back", project_path(@project), class: "btn btn-light"%>
    </div>
</div> 

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
    <nav class = "navbar navbar-default" role = "navigation" >
        <div class = "container">
            <div class = "navbar-header">
                <button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class = "sr-only">Toggle navigation</span>
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                </button>
            </div>
        
            <div class = "collapse navbar-collapse" id = "bs-example-navbar-collapse-1">
                <ul class = "nav navbar-nav">
                    <% @details = current_user.email + " : " + current_user.type.to_s  %>
                    <li><%= link_to @details, root_path, class: 'Details'%></li>
                    <li><%= link_to "Account", edit_user_registration_path %></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                </ul>
            </div>
        </div> 
    </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugZilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class = "container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name} ") %>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/projects/_error.html.erb
<%= link_to projects_path, style: "float: right;" do%>
    <i class = "glyphicon glyphicon-remove"></i>
<% end %>
<% if @project.errors.any? %>
    <div id = "error_explanation">
        <h4>
            The following 
            <%= pluralize(@project.errors.count, "error") %>
            prohibited this project from being saved :
        </h4>
        <ul>
            <% @project.errors.full_messages.each do |message|%>
                <li><%= message %>.</li>
            <% end %>
        </ul>
    </div>
<% end %> 

app/views/projects/_form.html.erb
<%= form_with model: @project, html: {class: "text-center border border-light p-5"}, local: true do |f| %>        
    <div class = "form-group">
        <%= f.text_field :title, class: "form-control mb-4",placeholder: "Title" %>
    </div>
    <div class = "form-group">
        <%= f.text_area :description, class: 'form-control rounded-0', 
        id: 'exampleFormControlTextarea2', rows: '3', placeholder: 'Description'%>
    </div>
    <div class = "form-group">
        <%= f.text_area :code, class: 'form-control rounded-0',
        id: 'exampleFormControlTextarea2', rows: '10', placeholder: 'Enter your code here'%>
    </div>
    <%= f.submit class: "btn btn-info btn-block" %>
<% end %>
  
 

app/views/projects/edit.html.erb
<div class = "container">
    <div class = "jumbotron" style = "margin-top:3%;">
        <%= render "error" %>
        <p class = "h2 mb-4">Edit Project</p>
        <%= render "form" %> 
    </div>
</div> 

app/views/projects/index.html.erb
<div class = "container">
    <div class = "jumbotron">
        <h3>Your Projects</h3>
        <table class = "table table-borderless">
            <tr>
                <th scope = "col">Title</th>
                <th scope = "col">Description</th>
                <th scope = "col">Code</th>
                <th scope = "col"></th>
                <th scope = "col"></th>
                <th scope = "col"></th>
            </tr>
            <% @projects.each do |project| %>
                <tr>
                    <td><%= project.title %></td>
                    <td><%= project.description %></td>
                    <td><%= project.code %></td>
                    <td><%= link_to "Show", project_path(project) %></td>
                    <% if policy(project).edit? %>
                        <td><%= link_to "Edit", edit_project_path(project) %></td>
                    <% end %>
                    <% if policy(project).destroy? %>
                        <td><%= link_to "Destroy", project_path(project),
                                method: :delete,
                                data: { confirm: "Are you sure?"} %></td>
                    <% end %>
                </tr>
            <% end %>
        </table>
        <% if policy(Project).create?%>
            <%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
        <% end %>
    </div>
</div> 

  

app/views/projects/new.html.erb
<div class = "container">
    <div class = "jumbotron" style = "margin-top:3%;">
        <%= render "error" %>
        <p class = "h2 mb-4">New Project</p>
        <%= render "form" %> 
    </div>
</div> 

app/views/projects/show.html.erb
<div class = "container">
    <div class = "jumbotron" style = "margin-top:3%;">
        <p>
            <strong>Title:</strong>
            <%= @project.title %>
        </p>
        <p>
            <strong>Description:</strong>
            <%= @project.description %>
        </p>
        <p>
            <strong>Code:</strong>
            <%= @project.code %>
        </p>
        <% if @project.qas.length + @project.developers.length > 0  %>
            <h3>Assigned QAs/Developers on this project</h3>
            <table class = "table table-borderless">
                <tr>
                    <th scope = "col">Email</th>
                    <th scope = "col">Role</th>
                    <th scope = "col"></th>
                </tr>
            
                <% @project.developers.each do |user| %>
                    <tr>
                        <td><%= user.email %></td>
                        <td><%= user.type %></td>
                        <% if policy(@project).remove_user? %>
                            <td><%= link_to "Remove", remove_user_project_path(:user_id => user.id, :project_id => @project.id) %></td>
                        <% end %>
                    </tr>
                <% end %>
                <% @project.qas.each do |user| %>
                    <tr>
                        <td><%= user.email %></td>
                        <td><%= user.type %></td>
                        <% if policy(@project).remove_user? %>
                            <td><%= link_to "Remove", remove_user_project_path(:user_id => user.id, :project_id => @project.id) %></td>
                        <% end %>
                    </tr>
                <% end %> 
            </table>
        <% end %>
        <% if @project.bugs.length > 0 %>
            <h2>Bugs</h2>
            <table class = "table table-borderless">
                <tr>
                    <th scope = "col">Bug Title</th>
                    <th scope = "col">Deadline</th>
                    <th scope = "col">Type</th>
                    <th scope = "col">Status</th>
                    <th scope = "col"></th>
                    <th scope = "col"></th>
                    <th scope = "col"></th>
                </tr>
                <%= render @project.bugs %>
            </table>
        <% end %>
        <%= link_to "Back", projects_path, class: "btn btn-light"%>
        <% if policy(@project).edit? %>
            <%= link_to "Edit", edit_project_path( @project ), class: "btn btn-light"%>
        <% end %>
        <% if policy(@project.bugs.new).new? %>
            <%= link_to "Add Bugs", new_project_bugs_path(@project), class: "btn btn-light"%>
        <% end %>
        <% if policy(@project).assign_user? %>
            <%= link_to "Assign Developer/QA",users_projects_path(:id => @project.id), class: "btn btn-light"%>
        <% end %>
    </div>
</div> 

app/views/projects/users.html.erb
<div class = "container">
    <div class = "jumbotron">
        <h3>All Developer/QAs</h3>
        <table class = "table table-borderless">
            <tr>
                <th scope = "col">Email</th>
                <th scope = "col">Role</th>
                <th scope = "col"></th>
            </tr>
            <% @users.each do |user| %>
                <tr>
                    <td><%= user.email %></td>
                    <td><%= user.type %></td>
                    <td><%= link_to "Assign", assign_user_project_path(:user_id => user.id, :id => @project.id) %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div> 